import type { ReactNode } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixLabelAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixLabelThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Aurora'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight'
  | 'Crimson'
  | 'Obsidian';

/*--!/--*/

// Edit here safely

export interface DyvixLabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  children: ReactNode;
  className?: string;
  htmlFor?: string;
  theme?: DyvixLabelThemes | null | undefined;
  animation?: DyvixLabelAnimation | null | undefined;
  background?: string;
  color?: string;
  style?: React.CSSProperties;
}
