import type { ReactNode } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixTableAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixTableThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Aurora'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight'
  | 'Crimson'
  | 'Obsidian'
  | 'Cosmos'
  | 'Sakura'
  | 'Volcanic';

/*--!/--*/

// Edit here safely

export interface DyvixConfigColumnsProps<T = Record<string, any>> {
  key: (keyof T & string) | string;
  label: string;
  sortable?: boolean;
}
export type DyvixConfigDataProps = Record<string, any>;

export interface DyvixTableProps<
  T extends Record<string, any> = DyvixConfigDataProps
> {
  children?: ReactNode;
  className?: string;
  animation?: DyvixTableAnimation | null;
  theme?: DyvixTableThemes | null | undefined;
  columns?: DyvixConfigColumnsProps<T>[];
  data?: T[];
  style?: React.CSSProperties;
  background?: string;
  color?: string;
}
