import type React from 'react';

//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixMarqueeAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

/*--!/--*/
// Edit here safely

export interface DyvixConfigItemsProps {
  label: string | React.ReactNode;
  href?: string;
}

export interface DyvixMarqueeItemProps {
  children: React.ReactNode;
  className?: string;
  href?: string;
  onClick?: Function;
  style?: React.CSSProperties;
}

export interface DyvixMarqueeProps {
  children?: React.ReactNode;
  className?: string;
  repeat?: number;
  animation?: DyvixMarqueeAnimation | null;
  speed?: number;
  pauseOnHover?: boolean;
  items?: DyvixConfigItemsProps[];
  timeline?: gsap.core.Timeline | null;
  style?: React.CSSProperties;
}
