import type React from 'react';

//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.
/*--!/--*/
// Edit here safely

export interface DyvixMarqueeItemProps {
  children: React.ReactNode;
  className?: string;
  href?: string;
  onClick?: Function;
  style?: React.CSSProperties;
}

export interface DyvixMarqueeProps {
  children?: React.ReactNode;
  className?: string;
}
