import type { InputHTMLAttributes, ReactNode } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixFileAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixFileThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Aurora'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight'
  | 'Crimson'
  | 'Obsidian'
  | 'Coffee';

/*--!/--*/

// Edit here safely

export interface DyvixFileProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  theme?: DyvixFileThemes | null;
  className?: string;
  animation?: DyvixFileAnimation | null;
  background?: string;
  color?: string;
  multiple?: boolean;
  accept?: string;
  onUpload?: (files: File | FileList) => void;
  style?: React.CSSProperties;
  timeline?: gsap.core.Timeline | null;
}
