import type { ReactNode } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixNavAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixNavThemes = 'Singularity' | 'Ember';

/*--!/--*/

// Edit here safely

interface DyvixConfigBrandProps {
  label: string;
  href?: string;
  onClick?: Function;
}
interface DyvixConfigItemsProps {
  label: string;
  href?: string;
  onClick?: Function;
}

export interface DyvixNavProps {
  children?: ReactNode;
  className?: string;
  animation?: DyvixNavAnimation | null;
  microanimation?: DyvixNavAnimation | null;
  theme?: DyvixNavThemes | null;
  brand?: DyvixConfigBrandProps;
  items?: DyvixConfigItemsProps[];
}
