import type {
  Dispatch,
  InputEventHandler,
  ReactNode,
  SetStateAction
} from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixModalAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixModalThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Aurora'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight'
  | 'Crimson'
  | 'Obsidian'
  | 'Coffee'
  | 'Cosmos'
  | 'Sakura'
  | 'Volcanic';

export type DyvixModalTypes = 'auth' | 'form';

export type DyvixModalPresets =
  'Register' | 'Login' | 'ForgotPassword' | 'ResetPassword' | 'ChangePassword';

export type DyvixModalElementTypes =
  | 'text'
  | 'email'
  | 'password'
  | 'search'
  | 'url'
  | 'tel'
  | 'textarea'
  | 'select'
  | 'd-select'
  | 'autocomplete'
  | 'checkbox'
  | 'radio'
  | 'file';

export type DyvixModalValidators =
  'email' | 'password' | 'number' | 'url' | 'mandatory' | 'date';

/*--!/--*/

// Edit here safely

type DyvixModalValidatorsWithRegex = DyvixModalValidators | `$R${string}`;

export interface DyvixElements {
  type: DyvixModalElementTypes;
  amount: number;
  placeholder: string[] | string;
  id?: string[] | string;
  name: string[] | string;
  validation?: DyvixModalValidatorsWithRegex[] | DyvixModalValidatorsWithRegex;
  match?: string[] | string;
  options?: string[] | string[][];
}

export interface NormalizedDyvixElements extends Omit<
  DyvixElements,
  'placeholder' | 'id' | 'name' | 'match' | 'options' | 'validation'
> {
  placeholder: string[];
  id?: string[];
  name: string[];
  validation?: DyvixModalValidatorsWithRegex[];
  match?: string[];
  options?: string[][];
}

export interface DyvixModalProps {
  title: string;
  type?: DyvixModalTypes;
  elements?: DyvixElements[];
  preset?: DyvixModalPresets;
  theme?: DyvixModalThemes | null;
  background?: string;
  animation?: DyvixModalAnimation | null;
  Id?: string;
  dynamicPositioning?: boolean;
  className?: string;
  onSubmit?: (data: Record<string, any>) => void;
  onChange?: (data: Record<string, any>) => void;
  onClose?: () => void;
  style?: React.CSSProperties;
}
