//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export const DYVIX_MODAL_THEME = 
 {
  "SINGULARITY": "Singularity",
  "INDUSTRIAL": "Industrial",
  "EMBER": "Ember",
  "FROST": "Frost",
  "BLADE": "Blade",
  "NEON": "Neon",
  "AURORA": "Aurora",
  "SUNSET": "Sunset",
  "OCEAN": "Ocean",
  "FOREST": "Forest",
  "MIDNIGHT": "Midnight"
}
export const DYVIX_MODAL_TYPE = 
 {
  "AUTH": "auth",
  "FORM": "form"
}
export const DYVIX_GLOBAL_ANIMATION = 
 {
  "FADE": "fade",
  "BUBBLE": "bubble",
  "ZOOM": "zoom",
  "UNFOLD": "unfold",
  "GLITCH": "glitch",
  "PULSE": "pulse",
  "AURORA": "aurora",
  "DROP": "drop",
  "FLIP": "flip",
  "GLIDE": "glide",
  "DRIFT": "drift"
}
export const DYVIX_MODAL_VALIDATION_PRESET = 
 {
  "EMAIL": "email",
  "PASSWORD": "password",
  "NUMBER": "number",
  "URL": "url"
}
export const DYVIX_MODAL_ELEMENT = 
 {
  "TEXT": "text",
  "EMAIL": "email",
  "PASSWORD": "password",
  "SEARCH": "search",
  "URL": "url",
  "TEL": "tel",
  "SELECT": "select",
  "D_SELECT": "d-select",
  "AUTOCOMPLETE": "autocomplete",
  "CHECKBOX": "checkbox"
}