//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export const DYVIX_GLOBAL_THEME = {
  SINGULARITY: 'Singularity',
  INDUSTRIAL: 'Industrial',
  EMBER: 'Ember',
  FROST: 'Frost',
  BLADE: 'Blade',
  NEON: 'Neon',
  AURORA: 'Aurora',
  SUNSET: 'Sunset',
  OCEAN: 'Ocean',
  FOREST: 'Forest',
  MIDNIGHT: 'Midnight',
  CRIMSON: 'Crimson',
  OBSIDIAN: 'Obsidian',
  COFFEE: 'Coffee',
  COSMOS: 'Cosmos',
  SAKURA: 'Sakura',
  VOLCANIC: 'Volcanic'
};
export const DYVIX_MODAL_TYPE = {
  AUTH: 'auth',
  FORM: 'form'
};
export const DYVIX_GLOBAL_ANIMATION = {
  FADE: 'fade',
  BUBBLE: 'bubble',
  ZOOM: 'zoom',
  UNFOLD: 'unfold',
  GLITCH: 'glitch',
  PULSE: 'pulse',
  AURORA: 'aurora',
  DROP: 'drop',
  FLIP: 'flip',
  GLIDE: 'glide',
  DRIFT: 'drift',
  FLOAT: 'float',
  SWING: 'swing',
  SLIDERIGHT: 'slideRight',
  SPIRAL: 'spiral',
  BOUNCE: 'bounce'
};
export const DYVIX_MODAL_VALIDATION_PRESET = {
  EMAIL: 'email',
  PASSWORD: 'password',
  NUMBER: 'number',
  URL: 'url',
  MANDATORY: 'mandatory',
  DATE: 'date'
};
export const DYVIX_MODAL_ELEMENT = {
  TEXT: 'text',
  EMAIL: 'email',
  PASSWORD: 'password',
  SEARCH: 'search',
  URL: 'url',
  TEL: 'tel',
  TEXTAREA: 'textarea',
  SELECT: 'select',
  D_SELECT: 'd-select',
  AUTOCOMPLETE: 'autocomplete',
  CHECKBOX: 'checkbox',
  RADIO: 'radio',
  FILE: 'file'
};
export const DYVIX_MODAL_PRESET = {
  REGISTER: 'Register',
  LOGIN: 'Login',
  FORGOTPASSWORD: 'ForgotPassword',
  RESETPASSWORD: 'ResetPassword',
  CHANGEPASSWORD: 'ChangePassword'
};
