import type {
  Dispatch,
  InputEventHandler,
  ReactNode,
  SetStateAction
} from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixSelectAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixSelectThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight';

/*--!/--*/

// Edit here safely

export interface DyvixSelectProps extends Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  'type' | 'onChange' | 'onFocus' | 'onBlur' | 'onKeyDown'
> {
  elements: (string | number)[];
  type: 'select' | 'autocomplete';
  animation?: DyvixSelectAnimation | null;
  theme?: DyvixSelectThemes | null | undefined;
  style?: React.CSSProperties;
  onChange?: (value: string | number) => void;
  onFocus?: React.FocusEventHandler<HTMLInputElement>;
  onBlur?: React.FocusEventHandler<HTMLInputElement>;
  onKeyDown?: React.KeyboardEventHandler<HTMLInputElement>;
  background?: string;
  dropdownBackground?: string;
  color?: string;
  placeholder?: string;
  timeline?: gsap.core.Timeline | null;
}

export interface DyvixSelectEngineProps {
  elements: (string | number)[];
  is_open: boolean;
  is_rendered: boolean;
  selectedElement: string;
  placeholder?: string;
  style?: React.CSSProperties;
  controller: Dispatch<SetStateAction<DyvixSelectState>>;
  activeIndex: number;
  inputRef: React.RefObject<HTMLInputElement | null>;
  OnChangeCallback: (value: string | number) => void;
  type: string;
  background?: string;
  className?: string;
  activeOptionId?: string;
}

export interface DyvixSelectState {
  is_rendered: boolean;
  is_open: boolean;
  elements: (string | number)[];
  selected: string | number | undefined;
  activeIndex: number;
}
