import type { Dispatch, SetStateAction } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixSelectAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixSelectThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight';

export interface DyvixSelectBaseOverride {
  '--dyvix-select-color'?: string & {};
  '--dyvix-select-letter-spacing'?:
    '-0.02em' | '-0.01em' | '0em' | (string & {});
  '--dyvix-select-border-width'?: '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-select-transition'?: (string & {}) | 'none';
  '--dyvix-select-hover-color'?: string & {};
  '--dyvix-select-hover-border-width'?: '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-hover-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-hover-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-select-hover-transform'?:
    'scale(1.009)' | 'none' | 'translateY(1px)' | 'scale(0.98)' | (string & {});
}

export interface DyvixSelectDefaultOverride {
  '--dyvix-select-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-font-family'?:
    'Geist' | 'system-ui' | 'monospace' | (string & {});
  '--dyvix-select-font-size'?:
    '0.875rem' | '0.9rem' | '1rem' | '1.125rem' | (string & {});
  '--dyvix-select-font-weight'?: 400 | 500 | 600 | 700 | (string & {});
  '--dyvix-select-border-color'?: (string & {}) | 'transparent';
  '--dyvix-select-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-hover-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-hover-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-hover-border-color'?: (string & {}) | 'transparent';
}

export interface DyvixSelectWrapperOverride {
  '--dyvix-select-width'?: 'fit-content' | '100%' | 'auto' | (string & {});
  '--dyvix-select-height'?: 'fit-content' | '100%' | 'auto' | (string & {});
  '--dyvix-select-display'?:
    | 'inline-block'
    | 'block'
    | 'inline-flex'
    | 'flex'
    | 'inline'
    | 'grid'
    | 'none'
    | (string & {});
}

export interface DyvixSelectInputOverride {
  '--dyvix-select-input-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-input-border-color'?: (string & {}) | 'transparent';
  '--dyvix-select-input-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-input-color'?: string & {};
  '--dyvix-select-input-border-width'?: '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-input-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-input-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-select-input-hover-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-input-hover-border-color'?: (string & {}) | 'transparent';
  '--dyvix-select-input-hover-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-input-hover-color'?: string & {};
  '--dyvix-select-input-hover-border-width'?:
    '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-input-hover-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-input-hover-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-select-input-focus-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-input-focus-border-color'?: (string & {}) | 'transparent';
  '--dyvix-select-input-focus-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-input-focus-color'?: string & {};
  '--dyvix-select-input-focus-border-width'?:
    '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-input-focus-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-input-focus-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
}

export interface DyvixSelectDropdownOverride {
  '--dyvix-select-dropdown-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-dropdown-border-color'?: (string & {}) | 'transparent';
  '--dyvix-select-dropdown-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-dropdown-color'?: string & {};
  '--dyvix-select-dropdown-border-width'?:
    '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-dropdown-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-dropdown-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-select-dropdown-text-align'?:
    'left' | 'center' | 'right' | (string & {});
  '--dyvix-select-dropdown-max-height'?:
    '150px' | '200px' | '300px' | (string & {});
  '--dyvix-select-dropdown-webkit-scrollbar-thumb-bg'?: string & {};
  '--dyvix-select-dropdown-hover-bg'?: (string & {}) | 'transparent';
  '--dyvix-select-dropdown-hover-border-color'?: (string & {}) | 'transparent';
  '--dyvix-select-dropdown-hover-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-select-dropdown-hover-color'?: string & {};
  '--dyvix-select-dropdown-hover-border-width'?:
    '0px' | '1px' | '2px' | (string & {});
  '--dyvix-select-dropdown-hover-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-select-dropdown-hover-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
}

/*--!/--*/

// Edit here safely

export interface DyvixSelectProps extends Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  'type' | 'onChange' | 'onFocus' | 'onBlur' | 'onKeyDown'
> {
  elements: (string | number)[];
  type: 'select' | 'autocomplete';
  animation?: DyvixSelectAnimation | null;
  theme?: DyvixSelectThemes | null | undefined;
  style?: React.CSSProperties;
  onChange?: (value: string | number) => void;
  onFocus?: React.FocusEventHandler<HTMLInputElement>;
  onBlur?: React.FocusEventHandler<HTMLInputElement>;
  onKeyDown?: React.KeyboardEventHandler<HTMLInputElement>;
  background?: string;
  overrides?: DyvixSelectWrapperOverride &
    DyvixSelectBaseOverride &
    DyvixSelectDefaultOverride &
    DyvixSelectInputOverride &
    DyvixSelectDropdownOverride;
  dropdownBackground?: string;
  color?: string;
  placeholder?: string;
  timeline?: gsap.core.Timeline | null;
}

export interface DyvixSelectEngineProps {
  elements: (string | number)[];
  is_open: boolean;
  is_rendered: boolean;
  selectedElement: string;
  placeholder?: string;
  style?: React.CSSProperties;
  controller: Dispatch<SetStateAction<DyvixSelectState>>;
  activeIndex: number;
  inputRef: React.RefObject<HTMLInputElement | null>;
  OnChangeCallback: (value: string | number) => void;
  type: string;
  background?: string;
  className?: string;
  activeOptionId?: string;
}

export interface DyvixSelectState {
  is_rendered: boolean;
  is_open: boolean;
  elements: (string | number)[];
  selected: string | number | undefined;
  activeIndex: number;
}
