import type { ReactNode } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixButtonAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixButtonThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Aurora'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight'
  | 'Crimson'
  | 'Coffee'
  | 'Cosmos'
  | 'Sakura'
  | 'Volcanic';

/*--!/--*/

// Edit here safely

export interface DyvixButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string;
  background?: string;
  color?: string;
  theme?: DyvixButtonThemes | null | undefined;
  animation?: DyvixButtonAnimation | null | undefined;
  children: ReactNode;
  style?: React.CSSProperties;
}
