import type { ReactNode } from 'react';
//AUTO GENERATED BY DYVIX UI ENGINE - DO NOT MANUALLY EDIT.

export type DyvixButtonAnimation =
  | 'fade'
  | 'bubble'
  | 'zoom'
  | 'unfold'
  | 'glitch'
  | 'pulse'
  | 'aurora'
  | 'drop'
  | 'flip'
  | 'glide'
  | 'drift'
  | 'float'
  | 'swing'
  | 'slideRight'
  | 'spiral'
  | 'bounce';

export type DyvixButtonThemes =
  | 'Singularity'
  | 'Industrial'
  | 'Ember'
  | 'Frost'
  | 'Blade'
  | 'Neon'
  | 'Aurora'
  | 'Sunset'
  | 'Ocean'
  | 'Forest'
  | 'Midnight'
  | 'Crimson'
  | 'Obsidian'
  | 'Coffee'
  | 'Cosmos'
  | 'Sakura'
  | 'Volcanic';

export interface DyvixButtonBaseOverride {
  '--dyvix-button-padding'?:
    '8px 16px' | '10px 22px' | '12px 24px' | (string & {});
  '--dyvix-button-color'?: string & {};
  '--dyvix-button-letter-spacing'?:
    '-0.02em' | '-0.01em' | '0em' | (string & {});
  '--dyvix-button-border-width'?: '0px' | '1px' | '2px' | (string & {});
  '--dyvix-button-border-style'?:
    'solid' | 'dashed' | 'dotted' | 'double' | 'none' | (string & {});
  '--dyvix-button-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-button-transition'?: (string & {}) | 'none';
  '--dyvix-button-hover-color'?: string & {};
  '--dyvix-button-hover-transform'?:
    'none' | 'translateY(-1px)' | 'scale(1.02)' | (string & {});
  '--dyvix-button-hover-border-width'?: '0px' | '1px' | '2px' | (string & {});
  '--dyvix-button-hover-border-style'?:
    'solid' | 'dashed' | (string & {}) | 'none';
  '--dyvix-button-hover-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
  '--dyvix-button-active-transform'?:
    'none' | 'translateY(1px)' | 'scale(0.98)' | (string & {});
  '--dyvix-button-active-border-width'?: '0px' | '1px' | '2px' | (string & {});
  '--dyvix-button-active-border-style'?:
    'solid' | 'dashed' | (string & {}) | 'none';
  '--dyvix-button-active-color'?: string & {};
  '--dyvix-button-active-border-radius'?:
    '0px' | '4px' | '6px' | '8px' | '9999px' | (string & {});
}

export interface DyvixButtonWrapperOverride {
  '--dyvix-button-width'?: 'fit-content' | '100%' | 'auto' | (string & {});
  '--dyvix-button-height'?: 'fit-content' | '100%' | 'auto' | (string & {});
  '--dyvix-button-display'?:
    | 'inline-block'
    | 'block'
    | 'inline-flex'
    | 'flex'
    | 'inline'
    | 'grid'
    | 'none'
    | (string & {});
}

export interface DyvixButtonDefaultOverride {
  '--dyvix-button-bg'?: (string & {}) | 'transparent';
  '--dyvix-button-font-family'?:
    'Geist' | 'system-ui' | 'monospace' | (string & {});
  '--dyvix-button-font-size'?:
    '0.875rem' | '0.9rem' | '1rem' | '1.125rem' | (string & {});
  '--dyvix-button-font-weight'?: 400 | 500 | 600 | 700 | (string & {});
  '--dyvix-button-border-color'?: (string & {}) | 'transparent';
  '--dyvix-button-box-shadow'?:
    'none' | 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)' | (string & {});
  '--dyvix-button-hover-bg'?: (string & {}) | 'transparent';
  '--dyvix-button-hover-border-color'?: (string & {}) | 'transparent';
  '--dyvix-button-hover-box-shadow'?:
    'none' | '0 4px 12px rgba(0, 0, 0, 0.5)' | (string & {});
  '--dyvix-button-active-bg'?: (string & {}) | 'transparent';
  '--dyvix-button-active-border-color'?: (string & {}) | 'transparent';
  '--dyvix-button-active-box-shadow'?:
    'none' | '0 0 10px rgba(255, 255, 255, 0.3)' | (string & {});
}

/*--!/--*/

// Edit here safely

export interface DyvixButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string;
  background?: string;
  color?: string;
  theme?: DyvixButtonThemes | null | undefined;
  animation?: DyvixButtonAnimation | null | undefined;
  overrides?: DyvixButtonBaseOverride &
    DyvixButtonWrapperOverride &
    DyvixButtonDefaultOverride;
  children: ReactNode;
  style?: React.CSSProperties;
  timeline?: gsap.core.Timeline | null;
}
