name: Dyvix Quality check
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Run Prettier Format Suggestions
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write . --ignore-path .gitignore
          only_changed: true
          dry: false
